name: Container

on: workflow_dispatch

env:
  IMAGE_NAME: caligo
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ${{ secrets.HEROKU_APP }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login into Heroku Container registry
        run: heroku container:login

      - name: Push the image to Heroku
        run: heroku container:push $IMAGE_NAME -a $HEROKU_APP
        
      - name: Release image to Heroku
        run: heroku container:release $IMAGE_NAME -a $HEROKU_APP
